POST http://localhost:8081/chat HTTP/1.1
Content-Type: application/json
Authorization: 123456

{
  "chat_id": "3121f582-9f52-40b1-8ae2-2b6cee8ed12a",
  "user_id": "2",
  "user_message": "O que você faz?"
}




# POST http://localhost:8081/chat HTTP/1.1
# Content-Type: application/json
# Authorization: 123456

# {
#   "chat_id": "77ce3719-cf51-4042-b1b2-921e038c9451",
#   "user_id": "1",
#   "user_message": "continue"
# }


# POST http://localhost:8081/chat HTTP/1.1
# Content-Type: application/json
# Authorization: 123456

# {
#   "user_id": "1",
#   "user_message": "O que é gRPC?"
# }